services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: moneytracker-api
    ports:
      - "8080:8080"
    depends_on:
      - redis
    env_file:
      - .env
    volumes:
      - ./Database:/app/Database
    environment:
      - ASPNETCORE_URLS=http://+:8080

  redis:
    image: redis:7-alpine
    container_name: moneytracker-redis
    ports:
      - "6379:6379"