// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MoneyTracker.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260504142705_TransactionChanged2")]
    partial class TransactionChanged2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MoneyTracker.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ColorHex")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ColorHex = "#FF6B6B",
                            Icon = "🍔",
                            Name = "Food & Dining"
                        },
                        new
                        {
                            Id = 2,
                            ColorHex = "#4ECDC4",
                            Icon = "🚗",
                            Name = "Transportation"
                        },
                        new
                        {
                            Id = 3,
                            ColorHex = "#95E1D3",
                            Icon = "🏥",
                            Name = "Health"
                        },
                        new
                        {
                            Id = 4,
                            ColorHex = "#A8E6CF",
                            Icon = "📚",
                            Name = "Education"
                        },
                        new
                        {
                            Id = 5,
                            ColorHex = "#FFD3B6",
                            Icon = "🎮",
                            Name = "Entertainment"
                        },
                        new
                        {
                            Id = 6,
                            ColorHex = "#FFAAA5",
                            Icon = "💡",
                            Name = "Utilities"
                        },
                        new
                        {
                            Id = 7,
                            ColorHex = "#FF8B94",
                            Icon = "👕",
                            Name = "Clothing"
                        },
                        new
                        {
                            Id = 8,
                            ColorHex = "#8E99F3",
                            Icon = "🏠",
                            Name = "Housing"
                        },
                        new
                        {
                            Id = 9,
                            ColorHex = "#B19CD9",
                            Icon = "✈️",
                            Name = "Travel"
                        },
                        new
                        {
                            Id = 10,
                            ColorHex = "#52C41A",
                            Icon = "💰",
                            Name = "Salary"
                        },
                        new
                        {
                            Id = 11,
                            ColorHex = "#FAAD14",
                            Icon = "🎁",
                            Name = "Bonus"
                        },
                        new
                        {
                            Id = 12,
                            ColorHex = "#D9D9D9",
                            Icon = "📌",
                            Name = "Other"
                        });
                });

            modelBuilder.Entity("MoneyTracker.Models.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CategoryId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsIncome")
                        .HasColumnType("bit");

                    b.Property<int?>("TransactionCategoryId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<decimal>("Value")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("TransactionCategoryId");

                    b.HasIndex("UserId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("MoneyTracker.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1
                        });
                });

            modelBuilder.Entity("MoneyTracker.Models.Transaction", b =>
                {
                    b.HasOne("MoneyTracker.Models.Category", "TransactionCategory")
                        .WithMany()
                        .HasForeignKey("TransactionCategoryId");

                    b.HasOne("MoneyTracker.Models.User", "User")
                        .WithMany("Transactions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TransactionCategory");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MoneyTracker.Models.User", b =>
                {
                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
